#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
def countApplesAndOranges(s, t, a, b, apples, oranges):
    aps, ors = 0,0 
    if isinstance(apples, int):
        apples = list([apples])
    if isinstance(oranges, int):
        oranges = list([oranges])
    for apl in apples:
        apl = apl + a
        if apl in range(s,t+1):
            aps = aps+1
    for orng in oranges:
        orng = orng + b
        if orng in range(s,t+1):
            ors = ors+1
    print(aps)
    print(ors)

if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
