#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the dayOfProgrammer function below.
def dayOfProgrammer(year):
    d=256
    m31,m30 = 31,30
    
    if year > 1918 and (year%4 == 0 and year%100 != 0) or year%400 == 0:
        feb = 29
    elif year < 1918 and year%4 == 0:
        feb = 29
    elif year == 1918:
        feb = 15
    else:
        feb = 28
    for mon,d_mon in zip(['01','02','03','04','05','06','07','08','09','10','11','12'],[m31,feb, m31, m30, m31, m30,m31, m31, m30,m31,m30, m31]):
        if d>28:
            d = d-d_mon
        else:
            return(f'{d}.{mon}.{year}')
            break

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    year = int(input().strip())

    result = dayOfProgrammer(year)

    fptr.write(result + '\n')

    fptr.close()
