#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'pickingNumbers' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY a as parameter.
#

def pickingNumbers(a):
    a.sort()
    l = [a[0]]
    r = []
    for i in range(1,len(a)):
        l.append(a[i])
        if abs(max(l)-(min(l)))<=1:
            pass
        else:
            l = l[:-1]
            if len(l)>len(r):
                r = l
            l = [a[i]]
    if r == []:
        r = l
    return(len(r))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    a = list(map(int, input().rstrip().split()))

    result = pickingNumbers(a)

    fptr.write(str(result) + '\n')

    fptr.close()
