#!/bin/python3
import math
import os
import sys

#
# Complete the pageCount function below.
#
def pageCount(n, p):
    if p <= n/2:
        # start at the beginning of book
        if p%2 != 0:
            p -= 1
        return(f'{p/2:.0f}')
    else:
        # start at the end of book
        if p%2 != 0:
            p -= 1
        if n%2 != 0:
            n -= 1
        return(f'{(n-p)/2:.0f}')

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = int(input())

    result = pageCount(n, p)

    fptr.write(str(result) + '\n')

    fptr.close()
